name: Devcontainer

on:
  pull_request:
    paths:
      - ".devcontainer/**"

  push:
    paths:
      - ".devcontainer/**"

  workflow_dispatch:

env:
  registry: ghcr.io

jobs:
  push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - directory: .devcontainer
            dockerfile: Dockerfile
            image_name: devcontainers/kpi

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Install Cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.registry }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.registry }}
          username: ${{ github.actor }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.registry }}/${{ github.repository_owner }}/${{ matrix.image_name }}
          tags: |
            enable={{is_default_branch}},type=raw,value=latest
            event=branch,type=ref
            event=pr,type=ref
            type=schedule
            pattern={{major}},type=semver
            pattern={{major}}.{{minor},type=semver
            pattern={{version}},type=semver
            format=long,type=sha

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          cache-from: src=/tmp/.buildx-cache,type=local
          cache-to: dest=/tmp/.buildx-cache-new,mode=max,type=local
          context: ${{ matrix.directory }}
          file: ${{ matrix.directory }}/${{ matrix.dockerfile }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          provenance: true
          push: ${{ github.event_name != 'pull_request' }}
          sbom: true
          tags: ${{ steps.meta.outputs.tags }}

      # TODO: https://github.com/docker/build-push-action/issues/252
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Sign the published Docker image
        if: github.event_name != 'pull_request'
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign sign --yes \
            -a "ref=${{ github.sha }}" \
            -a "repo=${{ github.repository }}" \
            -a "workflow=${{ github.workflow }}" \
            "${{ env.registry }}/${{ github.repository_owner }}/${{ matrix.image_name }}@${{ steps.build-and-push.outputs.digest }}"
